CREATE TABLE [dbo].[BUFF_IMPORT_DATA]
(
    [ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    [DATA_TYPE] NVARCHAR(255) NOT NULL,
    [DATA_VALUE] NVARCHAR(MAX),
    [SYS_DATE] DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    [IS_ERROR] NVARCHAR(1),
    [ERROR_MESSAGE] NVARCHAR(MAX)
)

GO
