CREATE TABLE [dbo].[CURRENCY]
(
	[Id] INT IDENTITY (1, 1) NOT NULL, 
    [CODE] NVARCHAR(3) NOT NULL, 
    [NAME] NVARCHAR(255) NOT NULL,    
    [SHORT_NAME] NVARCHAR(3) NOT NULL
    CONSTRAINT [PK_CURRENCY] PRIMARY KEY ([Id])
)
GO

CREATE UNIQUE NONCLUSTERED INDEX [UK_CURRENCY_CODE] ON [dbo].[CURRENCY] ([CODE])
