CREATE TABLE [dbo].[ISIN_SECUR]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [ISIN] NVARCHAR(30) NOT NULL, 
    [NOMINAL] INT NULL, 
    [AUK_PROC] NCHAR(10) NULL, 
    [PGS_DATE] DATE NULL, 
    [RAZM_DATE] DATE NULL, 
    [CPTYPE] NVARCHAR(255) NULL, 
    [CPDESCR] NVARCHAR(255) NULL, 
    [PAY_PERIOD] NVARCHAR(255) NULL, 
    [CURRENCY_CODE] NVARCHAR(3) NULL, 
    [EMIT_OKPO] NVARCHAR(255) NULL, 
    [EMIT_NAME] NVARCHAR(255) NULL, 
    [CPTYPE_NKCPFR] NVARCHAR(255) NULL, 
    [CPCODE_CFI] NVARCHAR(255) NULL, 
    [TOTAL_BONDS] INT NULL
)

GO

CREATE UNIQUE INDEX [UK_ISIN_SECUR] ON [dbo].[ISIN_SECUR] ([ISIN])
