CREATE TABLE [dbo].[ISIN_SECUR_PAY]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [ISIN_SECUR_ID] INT NOT NULL, 
    [PAY_DATE] DATE NOT NULL, 
    [PAY_TYPE] INT NOT NULL, 
    [PAY_VAL] NUMERIC(38, 15) NULL, 
    CONSTRAINT [FK_ISIN_SECUR_PAY] FOREIGN KEY ([ISIN_SECUR_ID]) REFERENCES [ISIN_SECUR]([ID])
)

GO

CREATE UNIQUE INDEX [UK_ISIN_SECUR_PAY] ON [dbo].[ISIN_SECUR_PAY] ([ISIN_SECUR_ID],[PAY_DATE],[PAY_TYPE])
