CREATE TABLE [dbo].[KURS_SSIS]
(
    [ID] INT,
    [ID_EXT] INT NOT NULL DEFAULT (NEXT VALUE FOR dbo.SEQ_KURS_SSIS_ID_EXT),
    [SUBSYSTEM_CODE] NVARCHAR(255) NOT NULL,
    [CURRENCY_CODE] NVARCHAR(3),
    [KURS_DATE] DATE,
    [RATE] MONEY,
    [FORC] INT,
    [SYS_DATE] DATETIME2 NOT NULL DEFAULT SYSDATETIME(), 
    [EVENT_CODE] NVARCHAR NULL, 
    [ERROR_CODE] INT NULL, 
    [ERROR_MESSAGE] NVARCHAR(MAX) NULL, 
    [HASH_COLIMN] AS CAST(HASHBYTES('SHA2_512', CONCAT([ID_EXT],'|',[SUBSYSTEM_CODE])) AS VARBINARY(64)) PERSISTED
)

GO

CREATE UNIQUE INDEX [UK_KURS_SSIS] ON [dbo].[KURS_SSIS] ([ID_EXT],[SUBSYSTEM_CODE])

GO

CREATE UNIQUE INDEX [UK_KURS_SSIS_HASH] ON [dbo].[KURS_SSIS] ([HASH_COLIMN])
