CREATE TABLE [dbo].[KURS_HIST]
(
    [Id] INT PRIMARY KEY NOT NULL DEFAULT (NEXT VALUE FOR dbo.SEQ_KURS_HIST),
    [CURRENCY_CODE] NVARCHAR(3), 
    [KURS_DATE] DATE, 
    [RATE] MONEY, 
    [FORC] INT, 
    [SYS_DATE] DATETIME2 NULL DEFAULT SYSDATETIME(),
    [SUSER_NAME] NVARCHAR(MAX) DEFAULT SUSER_SNAME() NULL,
    [HOST_NAME] NVARCHAR(MAX) DEFAULT HOST_NAME() NULL,
    [ACTION] NVARCHAR(50) NULL
)

GO

CREATE TRIGGER [dbo].[TR_KURS_HIST_HIST]
    ON [dbo].[KURS_HIST]
    FOR DELETE, UPDATE
    AS
    BEGIN
        RAISERROR ('Запрещено изменять или удалять значения из таблицы - TR_KURS_HIST_HIST', 16, 10);
    END