CREATE TABLE [dbo].[KURS_SSIS]
(
    [ID] INT,
    [ID_EXT] INT NOT NULL DEFAULT (NEXT VALUE FOR dbo.SEQ_KURS_SSIS_ID_EXT),
    [SYBSYSTEM_CODE] NVARCHAR(255) NOT NULL,
    [CURRENCY_CODE] NVARCHAR(3),
    [KURS_DATE] DATE,
    [RATE] MONEY,
    [FORC] INT,
    [SYS_DATE] DATETIME2 NOT NULL DEFAULT SYSDATETIME()    
)

GO

CREATE UNIQUE INDEX [UK_KURS_SSIS] ON [dbo].[KURS_SSIS] ([ID_EXT],[SYBSYSTEM_CODE])

GO
