CREATE VIEW [dbo].[VIEW_KURS_REPORT]
	AS
WITH KURS_AVG_YEAR (PART_YEAR, CURRENCY_CODE, AVG_RATE) AS
(
  SELECT CONVERT(nvarchar(4), DATEPART(year,k.KURS_DATE)) AS PART_YEAR,
         k.CURRENCY_CODE,
         AVG(k.RATE/k.FORC) AS AVG_RATE
    FROM KURS k
GROUP BY CONVERT(nvarchar(4), DATEPART(year,k.KURS_DATE)), k.CURRENCY_CODE

),
KURS_AVG (PART_MONTH_DATE, CURRENCY_CODE, AVG_RATE) AS
                (
                SELECT f.PART_MONTH_DATE,
					   f.CURRENCY_CODE,
					   AVG(f.AVG_RATE) as AVG_RATE
				FROM (SELECT SUBSTRING(CONVERT(nvarchar(10), k.KURS_DATE, 23), 6, 5) as PART_MONTH_DATE,
							 k.CURRENCY_CODE,
							 (k.RATE/a.AVG_RATE)*100 as AVG_RATE
					  FROM KURS k
					  INNER JOIN KURS_AVG_YEAR a ON a.PART_YEAR = CONVERT(nvarchar(4), DATEPART(year,k.KURS_DATE)) AND a.CURRENCY_CODE = k.CURRENCY_CODE
                      ) f
				GROUP BY f.PART_MONTH_DATE, f.CURRENCY_CODE
),
KURS_AVG_YEAR_MAX (PART_YEAR) AS
(
  SELECT CONVERT(nvarchar(4), MAX(DATEPART(year,kk.KURS_DATE))) AS PART_YEAR
  FROM KURS kk
)
 SELECT k.KURS_DATE,
		k.CURRENCY_CODE,
		k.RATE,
		a.AVG_RATE as AVG_RATE
FROM KURS k
INNER JOIN KURS_AVG a ON a.CURRENCY_CODE = k.CURRENCY_CODE AND a.PART_MONTH_DATE = SUBSTRING(CONVERT(nvarchar(10), k.KURS_DATE, 23), 6, 5) AND a.AVG_RATE <= 100
INNER JOIN KURS_AVG_YEAR_MAX y ON y.PART_YEAR = CONVERT(nvarchar(4), DATEPART(year,k.KURS_DATE))
WHERE k.CURRENCY_CODE = '840'
