CREATE VIEW [dbo].[VIEW_KURS]
AS 
	SELECT k.CURRENCY_CODE,
	       c.SHORT_NAME as CURRENCY_SNAME,
		   c.NAME as CURRENCY_NAME,
		   k.KURS_DATE,
		   k.RATE,
		   k.FORC
	FROM [KURS] k
	INNER JOIN [CURRENCY] AS c ON c.CODE = k.CURRENCY_CODE
